export const STATUS_CHANGE = 'STATUS_CHANGE'

export const AIRCRAFT_CHANGE = 'AIRCRAFT_CHANGE'
export const AIRCRAFT_TYPE_CHANGE = 'AIRCRAFT_TYPE_CHANGE'

export const CARRIER_SELECT = 'CARRIER_SELECT'
