export const PAGE_CHANGE = 'PAGE_CHANGE'
export const MODEL_OPEN = 'MODEL_OPEN'
export const MODEL_CLOSE = 'MODEL_CLOSE'

export const AIRCRAFT_CHANGE = 'AIRCRAFT_CHANGE'
export const AIRCRAFT_TYPE_CHANGE = 'AIRCRAFT_TYPE_CHANGE'
export const AIRCRAFT_SKILL_CHANGE = 'AIRCRAFT_SKILL_CHANGE'
export const AIRCRAFT_FACTORY_CHANGE = 'AIRCRAFT_FACTORY_CHANGE'

export const CARRIER_SELECT = 'CARRIER_SELECT'
export const CARRIER_SLOT_SELECT = 'CARRIER_SLOT_SELECT'
export const CARRIER_DISPLAY = 'CARRIER_DISPLAY'

export const STATUS_INITIAL = 'STATUS_INITIAL'
export const STATUS_CHANGE = 'STATUS_CHANGE'