export const MODEL_OPEN = 'MODEL_OPEN'
export const MODEL_CLOSE = 'MODEL_CLOSE'
export const TOGGLE_CHANGE = 'TOGGLE_CHANGE'
export const DAY_CHANGE = 'DAY_CHANGE'
export const SORT_CHANGE = 'SORT_CHANGE'
export const TYPE_CHANGE = 'TYPE_CHANGE'
